<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SampleCompaniesSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('companies')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        $companies = [
            [
                'name' => 'MTN Cameroun SA',
                'trade_name' => 'MTN',
                'legal_form' => 'sa',
                'description_fr' => 'Operateur de telephonie mobile leader au Cameroun, offrant des services de voix, donnees et Mobile Money (MoMo) a plus de 9 millions d\'abonnes.',
                'description_en' => 'Leading mobile telecommunications operator in Cameroon, offering voice, data and Mobile Money (MoMo) services to over 9 million subscribers.',
                'rccm_number' => 'RC/DLA/2000/B/1234',
                'niu_number' => 'M012600012345G',
                'share_capital' => 45000000000,
                'region_id' => 5, 'city_id' => 1,
                'address' => 'Avenue du General de Gaulle, Douala',
                'phone' => '+237 222 50 70 00',
                'email' => 'contact@mtn.cm',
                'website' => 'https://www.mtn.cm',
                'incorporation_date' => '2000-07-01',
                'employee_count_min' => 1000, 'employee_count_max' => 5000,
                'verification_status' => 'certified',
                'is_featured' => true,
            ],
            [
                'name' => 'Societe Generale Cameroun',
                'trade_name' => 'SG Cameroun',
                'legal_form' => 'sa',
                'description_fr' => 'Banque commerciale de reference au Cameroun avec un reseau de 40 agences et plus de 300 000 clients particuliers et entreprises.',
                'description_en' => 'Reference commercial bank in Cameroon with a network of 40 branches and over 300,000 individual and corporate clients.',
                'rccm_number' => 'RC/DLA/1998/B/4567',
                'niu_number' => 'M012500056789H',
                'share_capital' => 15000000000,
                'region_id' => 5, 'city_id' => 1,
                'address' => 'Rue Joss, Bonanjo, Douala',
                'phone' => '+237 233 43 40 00',
                'email' => 'contact@sgcameroun.cm',
                'website' => 'https://www.societegenerale.cm',
                'incorporation_date' => '1998-03-15',
                'employee_count_min' => 500, 'employee_count_max' => 1000,
                'verification_status' => 'certified',
                'is_featured' => true,
            ],
            [
                'name' => 'Brasseries du Cameroun',
                'trade_name' => 'SABC',
                'legal_form' => 'sa',
                'description_fr' => 'Premier groupe brassicole en Afrique centrale, producteur des marques Castel Beer, 33 Export, Guinness et Malta CC.',
                'description_en' => 'Premier brewing group in Central Africa, producing the brands Castel Beer, 33 Export, Guinness and Malta CC.',
                'rccm_number' => 'RC/DLA/1948/B/0001',
                'niu_number' => 'M011000001234A',
                'share_capital' => 20000000000,
                'region_id' => 5, 'city_id' => 1,
                'address' => 'Zone Industrielle de Bassa, Douala',
                'phone' => '+237 233 39 88 00',
                'email' => 'info@sabc.cm',
                'website' => 'https://www.brasseriesducameroun.cm',
                'incorporation_date' => '1948-05-06',
                'employee_count_min' => 2000, 'employee_count_max' => 5000,
                'verification_status' => 'certified',
                'is_featured' => true,
            ],
            [
                'name' => 'Orange Cameroun SA',
                'trade_name' => 'Orange',
                'legal_form' => 'sa',
                'description_fr' => 'Operateur de telecommunications multiservices proposant la telephonie mobile, la fibre optique et les services financiers Orange Money.',
                'description_en' => 'Multi-service telecommunications operator offering mobile telephony, fibre optics and Orange Money financial services.',
                'rccm_number' => 'RC/YAO/1999/B/2345',
                'niu_number' => 'M021200023456B',
                'share_capital' => 30000000000,
                'region_id' => 2, 'city_id' => 2,
                'address' => 'Rue Nachtigal, Yaounde',
                'phone' => '+237 222 23 60 00',
                'email' => 'client@orange.cm',
                'website' => 'https://www.orange.cm',
                'incorporation_date' => '1999-12-01',
                'employee_count_min' => 1000, 'employee_count_max' => 3000,
                'verification_status' => 'certified',
                'is_featured' => true,
            ],
            [
                'name' => 'Afriland First Bank',
                'trade_name' => 'Afriland',
                'legal_form' => 'sa',
                'description_fr' => 'Banque panafricaine fondee a Yaounde en 1987, specialisee dans le financement des PME et de l\'entrepreneuriat camerounais.',
                'description_en' => 'Pan-African bank founded in Yaounde in 1987, specializing in financing SMEs and Cameroonian entrepreneurship.',
                'rccm_number' => 'RC/YAO/1987/B/0156',
                'niu_number' => 'M020000015678C',
                'share_capital' => 8500000000,
                'region_id' => 2, 'city_id' => 2,
                'address' => 'Avenue Joseph Mballa Eloumden, Yaounde',
                'phone' => '+237 222 23 35 30',
                'email' => 'info@afrilandfirstbank.com',
                'website' => 'https://www.afrilandfirstbank.com',
                'incorporation_date' => '1987-09-23',
                'employee_count_min' => 500, 'employee_count_max' => 1000,
                'verification_status' => 'verified',
                'is_featured' => true,
            ],
            [
                'name' => 'CAMRAIL SA',
                'trade_name' => 'Camrail',
                'legal_form' => 'sa',
                'description_fr' => 'Concessionnaire du reseau ferroviaire camerounais, operant 1 000 km de voies ferrees reliant Douala, Yaounde, Ngaoundere et Kumba.',
                'description_en' => 'Concessionaire of the Cameroonian railway network, operating 1,000 km of railway connecting Douala, Yaounde, Ngaoundere and Kumba.',
                'rccm_number' => 'RC/DLA/1999/B/3456',
                'niu_number' => 'M012600034567D',
                'share_capital' => 25000000000,
                'region_id' => 5, 'city_id' => 1,
                'address' => 'Gare de Bessengue, Douala',
                'phone' => '+237 233 40 60 40',
                'email' => 'communication@camrail.net',
                'website' => 'https://www.camrail.net',
                'incorporation_date' => '1999-01-15',
                'employee_count_min' => 2000, 'employee_count_max' => 5000,
                'verification_status' => 'verified',
                'is_featured' => false,
            ],
            [
                'name' => 'CHOCOCAM SA',
                'trade_name' => 'Chococam',
                'legal_form' => 'sa',
                'description_fr' => 'Industrie agro-alimentaire specialisee dans la transformation du cacao camerounais en chocolats, confiseries et produits derives depuis 1972.',
                'description_en' => 'Agri-food industry specializing in the transformation of Cameroonian cocoa into chocolates, confectionery and derived products since 1972.',
                'rccm_number' => 'RC/DLA/1972/B/0089',
                'niu_number' => 'M010000008901E',
                'share_capital' => 4000000000,
                'region_id' => 5, 'city_id' => 1,
                'address' => 'Zone Industrielle, Bassa, Douala',
                'phone' => '+237 233 39 78 00',
                'email' => 'contact@chococam.cm',
                'website' => null,
                'incorporation_date' => '1972-04-12',
                'employee_count_min' => 200, 'employee_count_max' => 500,
                'verification_status' => 'verified',
                'is_featured' => false,
            ],
            [
                'name' => 'Cameroon Telecommunications',
                'trade_name' => 'CAMTEL',
                'legal_form' => 'other',
                'description_fr' => 'Entreprise publique de telecommunications, operateur historique des lignes fixes et fournisseur d\'acces Internet haut debit au Cameroun.',
                'description_en' => 'Public telecommunications company, historical operator of fixed lines and high-speed Internet access provider in Cameroon.',
                'rccm_number' => 'RC/YAO/1998/B/0001',
                'niu_number' => 'M020000000001F',
                'share_capital' => 50000000000,
                'region_id' => 2, 'city_id' => 2,
                'address' => 'Centre Administratif de Yaounde',
                'phone' => '+237 222 22 01 00',
                'email' => 'dg@camtel.cm',
                'website' => 'https://www.camtel.cm',
                'incorporation_date' => '1998-01-01',
                'employee_count_min' => 3000, 'employee_count_max' => 10000,
                'verification_status' => 'certified',
                'is_featured' => false,
            ],
            [
                'name' => 'TotalEnergies Marketing Cameroun',
                'trade_name' => 'TotalEnergies',
                'legal_form' => 'sa',
                'description_fr' => 'Distributeur de carburants, lubrifiants et services petroliers avec un reseau de plus de 150 stations-service a travers le Cameroun.',
                'description_en' => 'Distributor of fuels, lubricants and petroleum services with a network of over 150 service stations across Cameroon.',
                'rccm_number' => 'RC/DLA/1985/B/2890',
                'niu_number' => 'M012500028901G',
                'share_capital' => 6000000000,
                'region_id' => 5, 'city_id' => 1,
                'address' => 'Boulevard de la Liberte, Douala',
                'phone' => '+237 233 43 07 00',
                'email' => 'contact.cm@totalenergies.com',
                'website' => 'https://totalenergies.cm',
                'incorporation_date' => '1985-06-30',
                'employee_count_min' => 200, 'employee_count_max' => 500,
                'verification_status' => 'verified',
                'is_featured' => false,
            ],
            [
                'name' => 'Nexttel Cameroon',
                'trade_name' => 'Nexttel',
                'legal_form' => 'sa',
                'description_fr' => 'Troisieme operateur mobile au Cameroun avec le reseau 3G CDMA, offrant des services voix et data a prix competitifs.',
                'description_en' => 'Third mobile operator in Cameroon with a 3G CDMA network, offering voice and data services at competitive prices.',
                'rccm_number' => 'RC/DLA/2014/B/5678',
                'niu_number' => 'M012600056781H',
                'share_capital' => 12000000000,
                'region_id' => 5, 'city_id' => 1,
                'address' => 'Rue du Commerce, Douala',
                'phone' => '+237 233 40 00 70',
                'email' => 'support@nexttel.cm',
                'website' => 'https://www.nexttel.cm',
                'incorporation_date' => '2014-08-20',
                'employee_count_min' => 200, 'employee_count_max' => 500,
                'verification_status' => 'basic',
                'is_featured' => false,
            ],
            [
                'name' => 'Credit Communautaire d\'Afrique',
                'trade_name' => 'CCA Bank',
                'legal_form' => 'sa',
                'description_fr' => 'Banque de proximite dediee au financement des petites entreprises, artisans et commercants avec des produits financiers adaptes aux besoins locaux.',
                'description_en' => 'Community bank dedicated to financing small businesses, craftsmen and traders with financial products adapted to local needs.',
                'rccm_number' => 'RC/YAO/2003/B/4561',
                'niu_number' => 'M020200045612I',
                'share_capital' => 2500000000,
                'region_id' => 2, 'city_id' => 2,
                'address' => 'Quartier Melen, Yaounde',
                'phone' => '+237 222 20 35 60',
                'email' => 'contact@ccabank.cm',
                'website' => null,
                'incorporation_date' => '2003-11-02',
                'employee_count_min' => 100, 'employee_count_max' => 200,
                'verification_status' => 'verified',
                'is_featured' => false,
            ],
            [
                'name' => 'Agro-Pastoral Investment Company',
                'trade_name' => 'APIC',
                'legal_form' => 'sarl',
                'description_fr' => 'Societe d\'investissement agricole developpant des projets d\'elevage bovin, avicole et de cultures vivrieres dans les regions de l\'Adamaoua et du Nord.',
                'description_en' => 'Agricultural investment company developing cattle, poultry and food crop projects in the Adamaoua and North regions.',
                'rccm_number' => 'RC/NGD/2010/B/1234',
                'niu_number' => 'M031400012345J',
                'share_capital' => 500000000,
                'region_id' => 1, 'city_id' => null,
                'address' => 'Ngaoundere, Adamaoua',
                'phone' => '+237 699 45 67 89',
                'email' => 'info@apic-cameroun.cm',
                'website' => null,
                'incorporation_date' => '2010-03-18',
                'employee_count_min' => 50, 'employee_count_max' => 200,
                'verification_status' => 'basic',
                'is_featured' => false,
            ],
            [
                'name' => 'Cameroon Housing Bank',
                'trade_name' => 'CHB',
                'legal_form' => 'sa',
                'description_fr' => 'Banque specialisee dans le financement immobilier et les credits habitat destines aux menages et promoteurs immobiliers camerounais.',
                'description_en' => 'Bank specializing in real estate financing and housing loans for Cameroonian households and property developers.',
                'rccm_number' => 'RC/YAO/2015/B/3456',
                'niu_number' => 'M020100034567K',
                'share_capital' => 5000000000,
                'region_id' => 2, 'city_id' => 2,
                'address' => 'Avenue Monseigneur Vogt, Yaounde',
                'phone' => '+237 222 23 45 00',
                'email' => 'info@chb.cm',
                'website' => 'https://www.chb.cm',
                'incorporation_date' => '2015-07-14',
                'employee_count_min' => 100, 'employee_count_max' => 200,
                'verification_status' => 'verified',
                'is_featured' => false,
            ],
            [
                'name' => 'African Timber and Plywood',
                'trade_name' => 'ATP',
                'legal_form' => 'sarl',
                'description_fr' => 'Entreprise forestiere et de transformation du bois operant dans la region du Sud avec des concessions forestieres certifiees FSC.',
                'description_en' => 'Forestry and wood processing company operating in the South region with FSC-certified forest concessions.',
                'rccm_number' => 'RC/KRI/2001/B/0234',
                'niu_number' => 'M091200002345L',
                'share_capital' => 3000000000,
                'region_id' => 9, 'city_id' => null,
                'address' => 'Kribi, Region du Sud',
                'phone' => '+237 699 67 89 01',
                'email' => 'contact@atp-cameroon.cm',
                'website' => null,
                'incorporation_date' => '2001-09-05',
                'employee_count_min' => 200, 'employee_count_max' => 500,
                'verification_status' => 'basic',
                'is_featured' => false,
            ],
            [
                'name' => 'Cameroon Microfinance Alliance',
                'trade_name' => 'CaMA',
                'legal_form' => 'cooperative',
                'description_fr' => 'Reseau cooperatif de microfinance accompagnant les femmes entrepreneures et petits producteurs ruraux avec des prets de 50 000 a 5 000 000 FCFA.',
                'description_en' => 'Cooperative microfinance network supporting women entrepreneurs and small rural producers with loans from 50,000 to 5,000,000 FCFA.',
                'rccm_number' => 'RC/BFM/2008/B/0678',
                'niu_number' => 'M080800006789M',
                'share_capital' => 150000000,
                'region_id' => 8, 'city_id' => 3,
                'address' => 'Bafoussam, Region de l\'Ouest',
                'phone' => '+237 677 89 01 23',
                'email' => 'cama@microfinance.cm',
                'website' => null,
                'incorporation_date' => '2008-02-29',
                'employee_count_min' => 20, 'employee_count_max' => 50,
                'verification_status' => 'basic',
                'is_featured' => false,
            ],
            [
                'name' => 'Societe Camerounaise de Palmeraies',
                'trade_name' => 'SOCAPALM',
                'legal_form' => 'sa',
                'description_fr' => 'Agro-industriel specialise dans la culture du palmier a huile et la production d\'huile de palme, avec 37 000 ha de plantations au Cameroun.',
                'description_en' => 'Agro-industrial company specializing in oil palm cultivation and palm oil production, with 37,000 ha of plantations in Cameroon.',
                'rccm_number' => 'RC/DLA/1968/B/0023',
                'niu_number' => 'M010000000234N',
                'share_capital' => 18000000000,
                'region_id' => 5, 'city_id' => 1,
                'address' => 'Siege social, Mbanga, Mungo',
                'phone' => '+237 233 40 12 34',
                'email' => 'dg@socapalm.cm',
                'website' => null,
                'incorporation_date' => '1968-11-20',
                'employee_count_min' => 5000, 'employee_count_max' => 15000,
                'verification_status' => 'certified',
                'is_featured' => true,
            ],
            [
                'name' => 'Dibamba Power Development Company',
                'trade_name' => 'DPDC',
                'legal_form' => 'sa',
                'description_fr' => 'Producteur independant d\'electricite exploitant la centrale thermique de Dibamba d\'une puissance de 88 MW au service du reseau interconnecte Sud.',
                'description_en' => 'Independent power producer operating the Dibamba thermal power plant with a capacity of 88 MW serving the Southern Interconnected Grid.',
                'rccm_number' => 'RC/DLA/2009/B/7890',
                'niu_number' => 'M012600078901O',
                'share_capital' => 35000000000,
                'region_id' => 5, 'city_id' => 1,
                'address' => 'Dibamba, Wouri, Douala',
                'phone' => '+237 233 47 00 00',
                'email' => 'contact@dpdc.cm',
                'website' => null,
                'incorporation_date' => '2009-05-15',
                'employee_count_min' => 50, 'employee_count_max' => 200,
                'verification_status' => 'verified',
                'is_featured' => false,
            ],
            [
                'name' => 'Limbe Botanic Garden Foundation',
                'trade_name' => 'LBG',
                'legal_form' => 'association',
                'description_fr' => 'Organisation a but non lucratif preservant la biodiversite tropicale avec un jardin botanique de 200 ha et un centre de conservation des primates.',
                'description_en' => 'Non-profit organization preserving tropical biodiversity with a 200-hectare botanical garden and primate conservation center.',
                'rccm_number' => 'RC/LIM/1992/B/0056',
                'niu_number' => 'M100000000567P',
                'share_capital' => 0,
                'region_id' => 10, 'city_id' => 4,
                'address' => 'P.O. Box 437, Limbe, South West',
                'phone' => '+237 233 33 26 14',
                'email' => 'info@lbgcameroon.org',
                'website' => 'https://www.lbgcameroon.org',
                'incorporation_date' => '1992-06-01',
                'employee_count_min' => 50, 'employee_count_max' => 100,
                'verification_status' => 'verified',
                'is_featured' => false,
            ],
            [
                'name' => 'Nkafu Policy Institute',
                'trade_name' => 'NPI',
                'legal_form' => 'association',
                'description_fr' => 'Think tank panafricain base a Yaounde, produisant des analyses de politiques publiques sur la gouvernance, l\'economie et le developpement durable.',
                'description_en' => 'Pan-African think tank based in Yaounde, producing public policy analyses on governance, economics and sustainable development.',
                'rccm_number' => 'RC/YAO/2016/B/0901',
                'niu_number' => 'M020000009012Q',
                'share_capital' => 0,
                'region_id' => 2, 'city_id' => 2,
                'address' => 'Bastos, Yaounde',
                'phone' => '+237 699 01 23 45',
                'email' => 'info@nkafu.org',
                'website' => 'https://www.nkafu.org',
                'incorporation_date' => '2016-10-10',
                'employee_count_min' => 10, 'employee_count_max' => 50,
                'verification_status' => 'basic',
                'is_featured' => false,
            ],
            [
                'name' => 'ENEO Cameroon SA',
                'trade_name' => 'ENEO',
                'legal_form' => 'sa',
                'description_fr' => 'Societe concessionnaire du service public de l\'electricite au Cameroun, assurant la production, le transport et la distribution d\'energie electrique.',
                'description_en' => 'Concessionaire company of the public electricity service in Cameroon, providing the production, transmission and distribution of electric energy.',
                'rccm_number' => 'RC/DLA/2014/B/0001',
                'niu_number' => 'M012600000001R',
                'share_capital' => 80000000000,
                'region_id' => 5, 'city_id' => 1,
                'address' => 'Rue de la Chambre de Commerce, Douala',
                'phone' => '+237 233 43 50 00',
                'email' => 'contact@eneocameroon.cm',
                'website' => 'https://www.eneocameroon.cm',
                'incorporation_date' => '2014-07-17',
                'employee_count_min' => 3000, 'employee_count_max' => 8000,
                'verification_status' => 'certified',
                'is_featured' => true,
            ],
        ];

        foreach ($companies as $data) {
            $data['id']         = \Illuminate\Support\Str::uuid()->toString();
            $data['slug']       = \Illuminate\Support\Str::slug($data['name']);
            $data['status']     = 'active';
            $data['view_count'] = rand(50, 5000);
            $data['rating_avg'] = round(rand(35, 50) / 10, 1);
            $data['rating_count'] = rand(5, 200);
            $data['created_at'] = now();
            $data['updated_at'] = now();

            DB::table('companies')->insert($data);
        }

        $this->command->info('20 sample Cameroon companies seeded.');
    }
}
