<?php

namespace Tests\Concerns;

use App\Modules\Auth\Models\User;
use App\Modules\Businesses\Models\Business;
use App\Modules\Events\Models\Event;
use App\Modules\Products\Models\Product;

/**
 * Minimal record builders for feature tests. forceCreate sidesteps
 * $fillable differences; uuid/slug are generated by the models' own
 * creating hooks.
 */
trait BuildsGalleryData
{
    protected function makeUser(array $attrs = []): User
    {
        return User::factory()->create($attrs);
    }

    protected function makeBusiness(?User $owner = null, array $attrs = []): Business
    {
        return Business::forceCreate(array_merge([
            'user_id' => ($owner ?? $this->makeUser())->id,
            'name_fr' => 'Entreprise ' . fake()->unique()->word(),
            'status'  => 'published',
        ], $attrs));
    }

    protected function makeProduct(?Business $business = null, array $attrs = []): Product
    {
        return Product::forceCreate(array_merge([
            'business_id' => ($business ?? $this->makeBusiness())->id,
            'name_fr'     => 'Produit ' . fake()->unique()->word(),
            'status'      => 'published',
        ], $attrs));
    }

    protected function makeEvent(array $attrs = []): Event
    {
        return Event::forceCreate(array_merge([
            'name_fr'      => 'Événement ' . fake()->unique()->word(),
            'starts_at'    => now()->addDays(10),
            'is_published' => true,
        ], $attrs));
    }
}
